## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false
matrix:
 allow_failures:
 - julia: nightly

env:
  global:
    - DOCUMENTER_DEBUG=true

after_success:
  # push coverage results to Coveralls
  - julia -e 'import Pkg; cd(Pkg.dir("Yao")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  # push coverage results to Codecov
  - julia -e 'import Pkg; cd(Pkg.dir("Yao")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
