name = "LegibleLambdas"
uuid = "f1f30506-32fe-5131-bd72-7c197988f9e5"
authors = ["MasonProtter <mason.protter@gmail.com>", "Roger-luo <hiroger@qq.com>"]
version = "0.2.1"

[deps]
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
julia = "~1.0.0"
MLStyle = "~0.3"
MacroTools = "~0.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
