name = "LegibleLambdas"
uuid = "7ce37f9a-c85f-11e8-0c1b-69e31115c485"
authors = ["MasonProtter <mason.protter@gmail.com>"]
version = "0.1.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
